using System;
using System.IO;
using System.Text;
using ConversaCore.TopicTool.Models;

namespace ConversaCore.TopicTool.Services
{
    /// <summary>
    /// Generates C# partial classes and supporting files for ConversaCore topics.
    /// For now this operates on raw file paths; VS project integration will come later.
    /// </summary>
    internal static class TopicCodeGenerator
    {
        public static void CreateNewTopic(string topicsRootFolder, TopicSpec spec)
        {
            if (string.IsNullOrWhiteSpace(topicsRootFolder))
                throw new ArgumentException("Topics root folder must be provided", nameof(topicsRootFolder));

            if (spec == null)
                throw new ArgumentNullException(nameof(spec));

            if (string.IsNullOrWhiteSpace(spec.Name))
                throw new ArgumentException("TopicSpec.Name must be set before generation.", nameof(spec));

            var topicFolderName = SanitizeFolderName(spec.Name);
            var topicFolder = Path.Combine(topicsRootFolder, topicFolderName);

            // Enforce partial-class pattern for any pre-existing topic files.
            TopicPartialPatternGuard.EnsurePartialPattern(topicFolder, spec);

            // Ensure folder structure
            Directory.CreateDirectory(topicFolder);
            Directory.CreateDirectory(Path.Combine(topicFolder, "Cards"));
            Directory.CreateDirectory(Path.Combine(topicFolder, "Models"));
            Directory.CreateDirectory(Path.Combine(topicFolder, "Documents"));

            // Spec file
            var specPath = TopicSpecStorage.GetDefaultSpecPath(topicFolder);
            TopicSpecStorage.Save(specPath, spec);

            // Code files
            var domainPath = Path.Combine(topicFolder, $"{spec.Name}.Domain.cs");
            var generatedPath = Path.Combine(topicFolder, $"{spec.Name}.Generated.cs");

            if (!File.Exists(domainPath))
            {
                var domainCode = GenerateDomainPartial(spec);
                File.WriteAllText(domainPath, domainCode, Encoding.UTF8);
            }

            var generatedCode = GenerateGeneratedPartial(spec);
            GeneratedCodeValidator.ValidateOrThrow(generatedCode);
            File.WriteAllText(generatedPath, generatedCode, Encoding.UTF8);
        }

        private static string GenerateDomainPartial(TopicSpec spec)
        {
            var ns = string.IsNullOrWhiteSpace(spec.Namespace)
                ? "Topics"
                : spec.Namespace;

            var className = GetTopicClassName(spec);

            var sb = new StringBuilder();
            sb.AppendLine("// AUTO-GENERATED ONCE: You own this file. The Topic Tool will not overwrite it.");
            sb.AppendLine("// Customize domain-specific behavior and helper methods here.");
            sb.AppendLine();
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            sb.AppendLine($"    public partial class {className}");
            sb.AppendLine("    {");
            sb.AppendLine("        // TODO: Add any custom methods, properties, or helper logic here.");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string GenerateGeneratedPartial(TopicSpec spec)
        {
            var ns = string.IsNullOrWhiteSpace(spec.Namespace)
                ? "Topics"
                : spec.Namespace;

            var className = GetTopicClassName(spec);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// This file is generated by the ConversaCore Topic Tool.");
            sb.AppendLine($"// Tool version: {AuthoringGuideResource.Version}.");
            sb.AppendLine("// Any changes may be lost when the tool regenerates this topic.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using Microsoft.Extensions.Logging;");
            sb.AppendLine("using ConversaCore.Context;");
            sb.AppendLine("using ConversaCore.TopicFlow.Core;");
            sb.AppendLine();
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            sb.AppendLine($"    public partial class {className} : TopicFlow");
            sb.AppendLine("    {");
            sb.AppendLine($"        public {className}(TopicWorkflowContext context, ILogger<{className}> logger, IConversationContext conversationContext)");
            sb.AppendLine("            : base(context, logger, conversationContext)");
            sb.AppendLine("        {");
            sb.AppendLine("            // TODO: Build the activity workflow here using the TopicFlow API.");
            sb.AppendLine("            // The TopicSpec can be used to inform the structure.");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        // Optional: override CanHandleAsync, RunAsync, etc. as needed.");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string GetTopicClassName(TopicSpec spec)
        {
            // Simple convention: &lt;Name&gt;Topic
            return string.Concat(spec.Name.Trim(), "Topic");
        }

        private static string SanitizeFolderName(string name)
        {
            foreach (var c in Path.GetInvalidFileNameChars())
            {
                name = name.Replace(c, '_');
            }

            return name;
        }
    }
}
