using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using ConversaCore.TopicTool.Models;

namespace ConversaCore.TopicTool.Services
{
    /// <summary>
    /// Generates C# topic files from a TopicDesignerDocument according to the v1.0
    /// Code Generation Mapping Specification.
    ///
    /// This implementation is deterministic and framework-aligned with the
    /// existing SampleTopic pattern, but intentionally conservative in terms
    /// of runtime behavior: activities are emitted as SimpleActivity stubs
    /// with rich comments, so the code compiles and documents the design
    /// without guessing internal ConversaCore APIs for each activity type.
    /// </summary>
    internal static class TopicDesignerCodeGenerator
    {
        /// <summary>
        /// Generates one .cs file per topic under the Topics folder.
        ///
        /// IMPORTANT: This method assumes the caller has already confirmed the
        /// destructive behavior (wiping existing topic files in the top-level
        /// Topics folder).
        /// </summary>
        /// <param name="projectRoot">Root folder of the host project.</param>
        /// <param name="document">In-memory TopicDesignerDocument.</param>
        /// <param name="rootNamespace">
        /// Optional root namespace; if provided, ".Topics" will be appended
        /// unless it already ends with ".Topics".
        /// </param>
        public static void GenerateTopics(string projectRoot, TopicDesignerDocument document, string? rootNamespace)
        {
            if (string.IsNullOrWhiteSpace(projectRoot))
                throw new ArgumentException("Project root must be provided", nameof(projectRoot));

            if (document == null)
                throw new ArgumentNullException(nameof(document));

            var topicsFolder = Path.Combine(projectRoot, "Topics");
            Directory.CreateDirectory(topicsFolder);

            // Destructive behavior: delete only top-level files, not subfolders.
            foreach (var file in Directory.GetFiles(topicsFolder, "*", SearchOption.TopDirectoryOnly))
            {
                File.Delete(file);
            }

            var ns = ComputeTopicsNamespace(rootNamespace);

            foreach (var topic in document.Topics.OrderBy(t => t.Name, StringComparer.OrdinalIgnoreCase))
            {
                if (string.IsNullOrWhiteSpace(topic.Name))
                {
                    // Skip unnamed topics; validation should have caught this earlier.
                    continue;
                }

                var topicName = topic.Name.Trim();
                var className = SanitizeIdentifier(topicName) + "Topic";
                var fileName = SanitizeFileName(topicName) + ".cs";
                var filePath = Path.Combine(topicsFolder, fileName);

                var code = GenerateTopicFile(ns, className, topicName, topic);
                GeneratedCodeValidator.ValidateOrThrow(code);
                File.WriteAllText(filePath, code, Encoding.UTF8);
            }
        }

        private static string ComputeTopicsNamespace(string? rootNamespace)
        {
            if (string.IsNullOrWhiteSpace(rootNamespace))
            {
                return "Topics";
            }

            var ns = rootNamespace.Trim();
            return ns.EndsWith(".Topics", StringComparison.Ordinal)
                ? ns
                : ns + ".Topics";
        }

        private static string GenerateTopicFile(string topicsNamespace, string className, string topicName, TopicModel topic)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// This file is generated by the ConversaCore Topic Management Tool.");
            sb.AppendLine("// Any changes may be lost when the tool regenerates this topic.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using ConversaCore.Context;");
            sb.AppendLine("using ConversaCore.Interfaces;");
            sb.AppendLine("using ConversaCore.Models;");
            sb.AppendLine("using ConversaCore.TopicFlow;");
            sb.AppendLine("using ConversaCore.TopicFlow.Activities;");
            sb.AppendLine("using Microsoft.Extensions.Logging;");
            sb.AppendLine();
            sb.AppendLine("using TopicFlowBase = ConversaCore.TopicFlow.TopicFlow;");
            sb.AppendLine();
            sb.AppendLine($"namespace {topicsNamespace};");
            sb.AppendLine();
            sb.AppendLine("/// <summary>");
            sb.AppendLine($"/// Auto-generated topic for '{topicName}'.");
            if (!string.IsNullOrWhiteSpace(topic.Description))
            {
                sb.AppendLine($"/// {topic.Description.Trim()}");
            }
            sb.AppendLine("/// The structure of this topic is defined by the TopicDesignerDocument model.");
            sb.AppendLine("/// </summary>");
            sb.AppendLine($"public partial class {className} : TopicFlowBase");
            sb.AppendLine("{");
            sb.AppendLine($"    private readonly ILogger<{className}> _logger;");
            sb.AppendLine();
            sb.AppendLine($"    public {className}(TopicWorkflowContext context, ILogger<{className}> logger, IConversationContext conversationContext)");
            sb.AppendLine("        : base(context, logger, \"" + topicName + "\")");
            sb.AppendLine("    {");
            sb.AppendLine("        _logger = logger;");
            sb.AppendLine("        BuildWorkflow();");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public override void Reset()");
            sb.AppendLine("    {");
            sb.AppendLine("        base.Reset();");
            sb.AppendLine("        BuildWorkflow();");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Builds the topic activity graph as defined by the designer model.");
            sb.AppendLine("    /// NOTE: v1 output uses SimpleActivity stubs to represent prompts, conditionals,");
            sb.AppendLine("    /// API calls, and adaptive cards. These stubs are deterministic and safe, and");
            sb.AppendLine("    /// can be replaced with richer ConversaCore activities in future versions.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    private void BuildWorkflow()");
            sb.AppendLine("    {");

            foreach (var activity in topic.Activities.OrderBy(a => a.Order))
            {
                EmitActivity(sb, activity);
            }

            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public override Task<TopicResult> RunAsync(CancellationToken cancellationToken = default)");
            sb.AppendLine("    {");
            sb.AppendLine("        _logger.LogInformation(\"[" + className + "] RunAsync starting (State={State})\", State);");
            sb.AppendLine("        return base.RunAsync(cancellationToken);");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public override Task<float> CanHandleAsync(string input, CancellationToken cancellationToken = default)");
            sb.AppendLine("    {");
            sb.AppendLine("        // TODO: Customize intent matching logic for this topic.");
            sb.AppendLine("        return Task.FromResult(0.0f);");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static void EmitActivity(StringBuilder sb, ActivityModel activity)
        {
            var id = string.IsNullOrWhiteSpace(activity.ActivityId)
                ? $"Activity_{activity.Order}"
                : activity.ActivityId.Trim();

            sb.AppendLine();
            sb.AppendLine($"        // Activity {activity.Order}: {activity.Type} ({id})");

            switch (activity)
            {
                case PromptActivityModel prompt:
                    EmitPromptActivity(sb, id, prompt);
                    break;

                case ConditionalActivityModel conditional:
                    EmitConditionalActivity(sb, id, conditional);
                    break;

                case ApiActivityModel api:
                    EmitApiActivity(sb, id, api);
                    break;

                case AdaptiveCardActivityModel card:
                    EmitAdaptiveCardActivity(sb, id, card);
                    break;

                default:
                    sb.AppendLine($"        Add(new SimpleActivity(\"{id}\", \"[UNSUPPORTED ACTIVITY TYPE: {activity.Type}]\"));");
                    break;
            }
        }

        private static void EmitPromptActivity(StringBuilder sb, string id, PromptActivityModel prompt)
        {
            var question = EscapeString(prompt.Question ?? string.Empty);
            sb.AppendLine($"        // Question: {prompt.Question}");
            sb.AppendLine($"        // AnswerType: {prompt.AnswerType}");

            if (!string.IsNullOrWhiteSpace(prompt.StoreResponseVariable))
            {
                sb.AppendLine($"        // Store response in variable: {prompt.StoreResponseVariable}");
            }

            if (prompt.Options.Count > 0)
            {
                sb.AppendLine("        // Options:");
                foreach (var option in prompt.Options)
                {
                    sb.AppendLine($"        //   - {option.Label} => {option.Value}");
                }
            }

            sb.AppendLine($"        Add(new SimpleActivity(\"{id}\", \"{question}\"));");
        }

        private static void EmitConditionalActivity(StringBuilder sb, string id, ConditionalActivityModel conditional)
        {
            sb.AppendLine($"        // Conditional on variable: {conditional.ConditionVariable}");
            sb.AppendLine("        // Branches:");
            foreach (var branch in conditional.Branches)
            {
                sb.AppendLine($"        //   if == '{branch.MatchValue}' => {branch.TargetActivityId}");
            }

            if (!string.IsNullOrWhiteSpace(conditional.DefaultTargetActivityId))
            {
                sb.AppendLine($"        //   default => {conditional.DefaultTargetActivityId}");
            }

            sb.AppendLine($"        Add(new SimpleActivity(\"{id}\", \"[CONDITIONAL PLACEHOLDER: implement routing based on {conditional.ConditionVariable}]\"));");
        }

        private static void EmitApiActivity(StringBuilder sb, string id, ApiActivityModel api)
        {
            sb.AppendLine($"        // API call to: {api.HttpMethod} {api.Endpoint}");
            if (api.Parameters.Count > 0)
            {
                sb.AppendLine("        // Parameters:");
                foreach (var kvp in api.Parameters)
                {
                    sb.AppendLine($"        //   {kvp.Key} = {kvp.Value}");
                }
            }

            if (!string.IsNullOrWhiteSpace(api.StoreResponseVariable))
            {
                sb.AppendLine($"        // Store response in variable: {api.StoreResponseVariable}");
            }

            sb.AppendLine($"        Add(new SimpleActivity(\"{id}\", \"[API PLACEHOLDER: call {EscapeString(api.Endpoint ?? string.Empty)}]\"));");
        }

        private static void EmitAdaptiveCardActivity(StringBuilder sb, string id, AdaptiveCardActivityModel card)
        {
            sb.AppendLine("        // Adaptive card template JSON is stored in designer model.");
            if (!string.IsNullOrWhiteSpace(card.StoreResponseVariable))
            {
                sb.AppendLine($"        // Store card submission in variable: {card.StoreResponseVariable}");
            }

            sb.AppendLine($"        Add(new SimpleActivity(\"{id}\", \"[ADAPTIVE CARD PLACEHOLDER]\"));");
        }

        private static string SanitizeFileName(string name)
        {
            foreach (var c in Path.GetInvalidFileNameChars())
            {
                name = name.Replace(c, '_');
            }

            return string.IsNullOrWhiteSpace(name) ? "Topic" : name;
        }

        private static string SanitizeIdentifier(string name)
        {
            if (string.IsNullOrWhiteSpace(name))
            {
                return "Topic";
            }

            var builder = new StringBuilder();
            foreach (var ch in name)
            {
                if (char.IsLetterOrDigit(ch) || ch == '_')
                {
                    builder.Append(ch);
                }
                else
                {
                    builder.Append('_');
                }
            }

            if (!char.IsLetter(builder[0]) && builder[0] != '_')
            {
                builder.Insert(0, '_');
            }

            return builder.ToString();
        }

        private static string EscapeString(string value)
        {
            return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }
    }
}
