// <auto-generated />
using System;
using InsuranceSemanticV2.Data.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InsuranceSemanticV2.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251204045515_AddAgentTrackingToLeads")]
    partial class AddAgentTrackingToLeads
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InsuranceSemanticV2.Core.Entities.LifeGoals", b =>
                {
                    b.Property<int>("LifeGoalsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LifeGoalsId"));

                    b.Property<string>("CoverExpensesString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayMortgageString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeaceOfMindString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrepareFutureString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<string>("ProtectLovedOnesString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnsureString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LifeGoalsId");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("LifeGoals");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Core.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CarrierId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("CarrierId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Core.Entities.ProductStateAvailability", b =>
                {
                    b.Property<int>("AvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AvailabilityId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AvailabilityId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductStateAvailabilities");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.Agent", b =>
                {
                    b.Property<int>("AgentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AgentId"));

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AvgMinutes")
                        .HasColumnType("int");

                    b.Property<int>("Calls")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AgentId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.AgentAvailability", b =>
                {
                    b.Property<int>("AgentAvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AgentAvailabilityId"));

                    b.Property<int>("AgentId")
                        .HasColumnType("int");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("AgentAvailabilityId");

                    b.HasIndex("AgentId");

                    b.ToTable("AgentAvailabilities");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.AgentCarrierAppointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<int>("AgentId")
                        .HasColumnType("int");

                    b.Property<int>("CarrierId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppointmentId");

                    b.HasIndex("AgentId");

                    b.HasIndex("CarrierId");

                    b.ToTable("AgentCarrierAppointments");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.AgentLicense", b =>
                {
                    b.Property<int>("LicenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LicenseId"));

                    b.Property<int>("AgentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LicenseId");

                    b.HasIndex("AgentId");

                    b.ToTable("AgentLicenses");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.AgentLogin", b =>
                {
                    b.Property<int>("AgentLoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AgentLoginId"));

                    b.Property<int>("AgentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AgentLoginId");

                    b.HasIndex("AgentId");

                    b.ToTable("AgentLogins");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.AgentSession", b =>
                {
                    b.Property<int>("AgentSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AgentSessionId"));

                    b.Property<int>("AgentId")
                        .HasColumnType("int");

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastActivityTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LogoutTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("AgentSessionId");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("IX_AgentSessions_AgentId");

                    b.HasIndex("ConnectionId")
                        .HasDatabaseName("IX_AgentSessions_ConnectionId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_AgentSessions_IsActive");

                    b.ToTable("AgentSessions");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.AssetsLiabilities", b =>
                {
                    b.Property<int>("AssetsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssetsId"));

                    b.Property<string>("AutoLoans")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreditCardDebt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HasHomeEquityValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeEquityAmount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvestmentsAmount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MortgageDebt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherDebt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<string>("RetirementAmount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SavingsAmount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentLoans")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssetsId");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("AssetsLiabilities");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.BeneficiaryInfo", b =>
                {
                    b.Property<int>("BeneficiaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BeneficiaryId"));

                    b.Property<DateTime?>("BeneficiaryDob")
                        .HasColumnType("datetime2");

                    b.Property<string>("BeneficiaryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BeneficiaryPercentage")
                        .HasColumnType("int");

                    b.Property<string>("BeneficiaryRelationship")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.HasKey("BeneficiaryId");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("BeneficiaryInfos");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.CaliforniaResident", b =>
                {
                    b.Property<int>("CaliforniaResidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaliforniaResidentId"));

                    b.Property<string>("CcpaAcknowledged")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CaliforniaResidentId");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("CaliforniaResidents");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.Carrier", b =>
                {
                    b.Property<int>("CarrierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarrierId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CarrierId");

                    b.ToTable("Carriers");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.CarrierStateCompliance", b =>
                {
                    b.Property<int>("CarrierStateComplianceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarrierStateComplianceId"));

                    b.Property<int>("CarrierId")
                        .HasColumnType("int");

                    b.Property<string>("RuleDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CarrierStateComplianceId");

                    b.HasIndex("CarrierId");

                    b.ToTable("CarrierStateCompliances");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.Compliance", b =>
                {
                    b.Property<int>("ComplianceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComplianceId"));

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TcpaConsent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ComplianceId");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("Compliances");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.ContactAttempt", b =>
                {
                    b.Property<int>("AttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttemptId"));

                    b.Property<DateTime>("AttemptTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeadId")
                        .HasColumnType("int");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AttemptId");

                    b.HasIndex("LeadId");

                    b.ToTable("ContactAttempts");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.ContactHealth", b =>
                {
                    b.Property<int>("ContactHealthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactHealthId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CurrentlyTakingMedications")
                        .HasColumnType("bit");

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HospitalizedPast5Years")
                        .HasColumnType("bit");

                    b.Property<string>("MedicalConditions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Medications")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<bool>("TobaccoUseLast12Months")
                        .HasColumnType("bit");

                    b.HasKey("ContactHealthId");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("ContactHealths");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.ContactInfo", b =>
                {
                    b.Property<int>("ContactInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactInfoId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ConsentContact")
                        .HasColumnType("bit");

                    b.Property<bool>("ContactMethodEither")
                        .HasColumnType("bit");

                    b.Property<bool>("ContactMethodEmail")
                        .HasColumnType("bit");

                    b.Property<bool>("ContactMethodPhone")
                        .HasColumnType("bit");

                    b.Property<bool>("ContactTimeAfternoon")
                        .HasColumnType("bit");

                    b.Property<bool>("ContactTimeAny")
                        .HasColumnType("bit");

                    b.Property<bool>("ContactTimeEvening")
                        .HasColumnType("bit");

                    b.Property<bool>("ContactTimeMorning")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactInfoId");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("ContactInfos");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.ContactPolicy", b =>
                {
                    b.Property<int>("ContactPolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactPolicyId"));

                    b.Property<TimeSpan>("AllowedEndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("AllowedStartTime")
                        .HasColumnType("time");

                    b.Property<int>("MaxAttemptsPerDay")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactPolicyId");

                    b.ToTable("ContactPolicies");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.CoverageIntent", b =>
                {
                    b.Property<int>("CoverageIntentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoverageIntentId"));

                    b.Property<string>("CoverageAmount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverageStartTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MonthlyBudget")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.HasKey("CoverageIntentId");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("CoverageIntents");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.Dependents", b =>
                {
                    b.Property<int>("DependentsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DependentsId"));

                    b.Property<bool>("AgeRange0To5")
                        .HasColumnType("bit");

                    b.Property<bool>("AgeRange13To17")
                        .HasColumnType("bit");

                    b.Property<bool>("AgeRange18To25")
                        .HasColumnType("bit");

                    b.Property<bool>("AgeRange25Plus")
                        .HasColumnType("bit");

                    b.Property<bool>("AgeRange6To12")
                        .HasColumnType("bit");

                    b.Property<string>("HasDependentsValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaritalStatusValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NoOfChildren")
                        .HasColumnType("int");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.HasKey("DependentsId");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("Dependents");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.Employment", b =>
                {
                    b.Property<int>("EmploymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmploymentId"));

                    b.Property<string>("EmploymentStatusValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HouseholdIncomeValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<string>("YearsEmployedValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmploymentId");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("Employments");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.HealthInfo", b =>
                {
                    b.Property<int>("HealthInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HealthInfoId"));

                    b.Property<string>("ConditionBloodPressure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConditionDiabetes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConditionHeart")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConditionNone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentMedications")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FamilyMedicalHistory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HealthInsurance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Height")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverallHealthStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<string>("TobaccoUse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HealthInfoId");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("HealthInfos");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.InsuranceContext", b =>
                {
                    b.Property<int>("ContextId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContextId"));

                    b.Property<string>("CoverageFor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverageGoal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EquityString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExistingLifeInsuranceCoverage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HasExistingLifeInsuranceString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeValueString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InsuranceTarget")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InsuranceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoanTermString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MonthlyMortgageString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MortgageBalanceString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.HasKey("ContextId");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("InsuranceContexts");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.Lead", b =>
                {
                    b.Property<int>("LeadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeadId"));

                    b.Property<DateTime?>("AppointmentDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AssignedAgentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("FollowUpRequired")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterestLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LastModifiedByAgentId")
                        .HasColumnType("int");

                    b.Property<string>("LeadIntent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeadSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeadUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("QualificationScore")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("LeadId");

                    b.HasIndex("AssignedAgentId");

                    b.HasIndex("LastModifiedByAgentId");

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.LeadAppointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<int>("LeadId")
                        .HasColumnType("int");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ScheduledFor")
                        .HasColumnType("datetime2");

                    b.HasKey("AppointmentId");

                    b.HasIndex("LeadId");

                    b.ToTable("LeadAppointments");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.LeadAuditLog", b =>
                {
                    b.Property<int>("LeadAuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeadAuditLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AgentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LeadId")
                        .HasColumnType("int");

                    b.HasKey("LeadAuditLogId");

                    b.HasIndex("AgentId");

                    b.HasIndex("LeadId");

                    b.ToTable("LeadAuditLogs");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.LeadCallback", b =>
                {
                    b.Property<int>("LeadCallbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeadCallbackId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeadId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("ScheduledTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("LeadCallbackId");

                    b.HasIndex("LeadId");

                    b.ToTable("LeadCallbacks");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.LeadFollowUp", b =>
                {
                    b.Property<int>("FollowUpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FollowUpId"));

                    b.Property<DateTime>("FollowUpDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeadId")
                        .HasColumnType("int");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FollowUpId");

                    b.HasIndex("LeadId");

                    b.ToTable("LeadFollowUps");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.LeadProfile", b =>
                {
                    b.Property<int>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfileId"));

                    b.Property<int>("LeadId")
                        .HasColumnType("int");

                    b.HasKey("ProfileId");

                    b.HasIndex("LeadId")
                        .IsUnique();

                    b.ToTable("LeadProfiles");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.LeadScore", b =>
                {
                    b.Property<int>("LeadScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeadScoreId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeadId")
                        .HasColumnType("int");

                    b.Property<string>("ScoreType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScoreValue")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("LeadScoreId");

                    b.HasIndex("LeadId");

                    b.ToTable("LeadScores");
                });

            modelBuilder.Entity("LeadInteraction", b =>
                {
                    b.Property<int>("LeadInteractionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeadInteractionId"));

                    b.Property<int?>("AgentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InteractionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LeadId")
                        .HasColumnType("int");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LeadInteractionId");

                    b.HasIndex("AgentId");

                    b.HasIndex("LeadId");

                    b.ToTable("LeadInteractions");
                });

            modelBuilder.Entity("LeadStatusHistory", b =>
                {
                    b.Property<int>("LeadStatusHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeadStatusHistoryId"));

                    b.Property<int?>("AgentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ChangedByAgentId")
                        .HasColumnType("int");

                    b.Property<int>("LeadId")
                        .HasColumnType("int");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LeadStatusHistoryId");

                    b.HasIndex("AgentId");

                    b.HasIndex("LeadId");

                    b.ToTable("LeadStatusHistories");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Core.Entities.LifeGoals", b =>
                {
                    b.HasOne("InsuranceSemanticV2.Data.Entities.LeadProfile", "Profile")
                        .WithOne("LifeGoals")
                        .HasForeignKey("InsuranceSemanticV2.Core.Entities.LifeGoals", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Core.Entities.Product", b =>
                {
                    b.HasOne("InsuranceSemanticV2.Data.Entities.Carrier", "Carrier")
                        .WithMany("Products")
                        .HasForeignKey("CarrierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrier");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Core.Entities.ProductStateAvailability", b =>
                {
                    b.HasOne("InsuranceSemanticV2.Core.Entities.Product", "Product")
                        .WithMany("StateAvailability")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.Agent", b =>
                {
                    b.HasOne("InsuranceSemanticV2.Data.Entities.Company", "Company")
                        .WithMany("Agents")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.AgentAvailability", b =>
                {
                    b.HasOne("InsuranceSemanticV2.Data.Entities.Agent", "Agent")
                        .WithMany("Availabilities")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.AgentCarrierAppointment", b =>
                {
                    b.HasOne("InsuranceSemanticV2.Data.Entities.Agent", "Agent")
                        .WithMany("CarrierAppointments")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InsuranceSemanticV2.Data.Entities.Carrier", "Carrier")
                        .WithMany("AgentAppointments")
                        .HasForeignKey("CarrierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Carrier");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.AgentLicense", b =>
                {
                    b.HasOne("InsuranceSemanticV2.Data.Entities.Agent", "Agent")
                        .WithMany("Licenses")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.AgentLogin", b =>
                {
                    b.HasOne("InsuranceSemanticV2.Data.Entities.Agent", "Agent")
                        .WithMany("Logins")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.AgentSession", b =>
                {
                    b.HasOne("InsuranceSemanticV2.Data.Entities.Agent", "Agent")
                        .WithMany("Sessions")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.AssetsLiabilities", b =>
                {
                    b.HasOne("InsuranceSemanticV2.Data.Entities.LeadProfile", "Profile")
                        .WithOne("AssetsLiabilities")
                        .HasForeignKey("InsuranceSemanticV2.Data.Entities.AssetsLiabilities", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.BeneficiaryInfo", b =>
                {
                    b.HasOne("InsuranceSemanticV2.Data.Entities.LeadProfile", "Profile")
                        .WithOne("BeneficiaryInfo")
                        .HasForeignKey("InsuranceSemanticV2.Data.Entities.BeneficiaryInfo", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.CaliforniaResident", b =>
                {
                    b.HasOne("InsuranceSemanticV2.Data.Entities.LeadProfile", "Profile")
                        .WithOne("CaliforniaResident")
                        .HasForeignKey("InsuranceSemanticV2.Data.Entities.CaliforniaResident", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.CarrierStateCompliance", b =>
                {
                    b.HasOne("InsuranceSemanticV2.Data.Entities.Carrier", "Carrier")
                        .WithMany("StateCompliances")
                        .HasForeignKey("CarrierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrier");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.Compliance", b =>
                {
                    b.HasOne("InsuranceSemanticV2.Data.Entities.LeadProfile", "Profile")
                        .WithOne("Compliance")
                        .HasForeignKey("InsuranceSemanticV2.Data.Entities.Compliance", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.ContactAttempt", b =>
                {
                    b.HasOne("InsuranceSemanticV2.Data.Entities.Lead", "Lead")
                        .WithMany("ContactAttempts")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.ContactHealth", b =>
                {
                    b.HasOne("InsuranceSemanticV2.Data.Entities.LeadProfile", "Profile")
                        .WithOne("ContactHealth")
                        .HasForeignKey("InsuranceSemanticV2.Data.Entities.ContactHealth", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.ContactInfo", b =>
                {
                    b.HasOne("InsuranceSemanticV2.Data.Entities.LeadProfile", "Profile")
                        .WithOne("ContactInfo")
                        .HasForeignKey("InsuranceSemanticV2.Data.Entities.ContactInfo", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.CoverageIntent", b =>
                {
                    b.HasOne("InsuranceSemanticV2.Data.Entities.LeadProfile", "Profile")
                        .WithOne("CoverageIntent")
                        .HasForeignKey("InsuranceSemanticV2.Data.Entities.CoverageIntent", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.Dependents", b =>
                {
                    b.HasOne("InsuranceSemanticV2.Data.Entities.LeadProfile", "Profile")
                        .WithOne("Dependents")
                        .HasForeignKey("InsuranceSemanticV2.Data.Entities.Dependents", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.Employment", b =>
                {
                    b.HasOne("InsuranceSemanticV2.Data.Entities.LeadProfile", "Profile")
                        .WithOne("Employment")
                        .HasForeignKey("InsuranceSemanticV2.Data.Entities.Employment", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.HealthInfo", b =>
                {
                    b.HasOne("InsuranceSemanticV2.Data.Entities.LeadProfile", "Profile")
                        .WithOne("HealthInfo")
                        .HasForeignKey("InsuranceSemanticV2.Data.Entities.HealthInfo", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.InsuranceContext", b =>
                {
                    b.HasOne("InsuranceSemanticV2.Data.Entities.LeadProfile", "Profile")
                        .WithOne("InsuranceContext")
                        .HasForeignKey("InsuranceSemanticV2.Data.Entities.InsuranceContext", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.Lead", b =>
                {
                    b.HasOne("InsuranceSemanticV2.Data.Entities.Agent", "AssignedAgent")
                        .WithMany("AssignedLeads")
                        .HasForeignKey("AssignedAgentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("InsuranceSemanticV2.Data.Entities.Agent", "LastModifiedByAgent")
                        .WithMany("ModifiedLeads")
                        .HasForeignKey("LastModifiedByAgentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AssignedAgent");

                    b.Navigation("LastModifiedByAgent");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.LeadAppointment", b =>
                {
                    b.HasOne("InsuranceSemanticV2.Data.Entities.Lead", "Lead")
                        .WithMany("Appointments")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.LeadAuditLog", b =>
                {
                    b.HasOne("InsuranceSemanticV2.Data.Entities.Agent", "Agent")
                        .WithMany("LeadAuditLogs")
                        .HasForeignKey("AgentId");

                    b.HasOne("InsuranceSemanticV2.Data.Entities.Lead", "Lead")
                        .WithMany("AuditLogs")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.LeadCallback", b =>
                {
                    b.HasOne("InsuranceSemanticV2.Data.Entities.Lead", "Lead")
                        .WithMany("Callbacks")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.LeadFollowUp", b =>
                {
                    b.HasOne("InsuranceSemanticV2.Data.Entities.Lead", "Lead")
                        .WithMany("FollowUps")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.LeadProfile", b =>
                {
                    b.HasOne("InsuranceSemanticV2.Data.Entities.Lead", "Lead")
                        .WithOne("Profile")
                        .HasForeignKey("InsuranceSemanticV2.Data.Entities.LeadProfile", "LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.LeadScore", b =>
                {
                    b.HasOne("InsuranceSemanticV2.Data.Entities.Lead", "Lead")
                        .WithMany("Scores")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("LeadInteraction", b =>
                {
                    b.HasOne("InsuranceSemanticV2.Data.Entities.Agent", "Agent")
                        .WithMany("LeadInteractions")
                        .HasForeignKey("AgentId");

                    b.HasOne("InsuranceSemanticV2.Data.Entities.Lead", "Lead")
                        .WithMany("Interactions")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("LeadStatusHistory", b =>
                {
                    b.HasOne("InsuranceSemanticV2.Data.Entities.Agent", "Agent")
                        .WithMany("LeadStatusChanges")
                        .HasForeignKey("AgentId");

                    b.HasOne("InsuranceSemanticV2.Data.Entities.Lead", "Lead")
                        .WithMany("StatusHistory")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Core.Entities.Product", b =>
                {
                    b.Navigation("StateAvailability");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.Agent", b =>
                {
                    b.Navigation("AssignedLeads");

                    b.Navigation("Availabilities");

                    b.Navigation("CarrierAppointments");

                    b.Navigation("LeadAuditLogs");

                    b.Navigation("LeadInteractions");

                    b.Navigation("LeadStatusChanges");

                    b.Navigation("Licenses");

                    b.Navigation("Logins");

                    b.Navigation("ModifiedLeads");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.Carrier", b =>
                {
                    b.Navigation("AgentAppointments");

                    b.Navigation("Products");

                    b.Navigation("StateCompliances");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.Company", b =>
                {
                    b.Navigation("Agents");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.Lead", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("AuditLogs");

                    b.Navigation("Callbacks");

                    b.Navigation("ContactAttempts");

                    b.Navigation("FollowUps");

                    b.Navigation("Interactions");

                    b.Navigation("Profile");

                    b.Navigation("Scores");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("InsuranceSemanticV2.Data.Entities.LeadProfile", b =>
                {
                    b.Navigation("AssetsLiabilities")
                        .IsRequired();

                    b.Navigation("BeneficiaryInfo")
                        .IsRequired();

                    b.Navigation("CaliforniaResident")
                        .IsRequired();

                    b.Navigation("Compliance")
                        .IsRequired();

                    b.Navigation("ContactHealth")
                        .IsRequired();

                    b.Navigation("ContactInfo")
                        .IsRequired();

                    b.Navigation("CoverageIntent")
                        .IsRequired();

                    b.Navigation("Dependents")
                        .IsRequired();

                    b.Navigation("Employment")
                        .IsRequired();

                    b.Navigation("HealthInfo")
                        .IsRequired();

                    b.Navigation("InsuranceContext")
                        .IsRequired();

                    b.Navigation("LifeGoals")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
