using ConversaCore;
using ConversaCore.BlazorTemplateHost.Configuration;
using ConversaCore.Interfaces;
using ConversaCore.Registration;
using ConversaCore.UI.Services;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddRazorPages();
builder.Services.AddServerSideBlazor();
builder.Services.AddScoped<IChatInteropService, ChatInteropService>();

var openAIApiKey = Environment.GetEnvironmentVariable("OPENAI_API_KEY") ?? "demo-key";
builder.Services
    .AddConversaCoreBuilder(
        openAIApiKey: openAIApiKey,
        embeddingModel: "text-embedding-3-small")
    .AddConversaCoreDomainTopics()
    .AddConversaCoreTools()
    .AddConversationRuntime(ConversaCoreTopicRegistration.SampleTopicId);

// Optional host services generated by the Topic Tool remain separate from
// conversation registration and orchestration.
builder.Services.AddConversaCoreDocumentIngestion();

var app = builder.Build();

if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
    app.UseHsts();
}

app.UseHttpsRedirection();
app.UseStaticFiles();
app.UseRouting();
app.MapBlazorHub();
app.MapFallbackToPage("/_Host");

app.Run();
