using ConversaCore.Context;
using ConversaCore.TopicFlow;
using ConversaCore.TopicFlow.Core;
using ConversaCore.Topics;
using InsuranceLeadsAgent.Topics;
using InsuranceLeadsAgent.Topics.SampleTopic;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

namespace InsuranceLeadsAgent.Configuration
{
    /// <summary>
    /// Central place for registering domain-specific ConversaCore topics.
    /// Program.cs should only need to call AddConversaCoreDomainTopics.
    /// </summary>
    public static class ConversaCoreTopicRegistration
    {
        public static void AddConversaCoreDomainTopics(this IServiceCollection services)
        {
            // ─────────────────────────────
            // 🔹 Helper to register topic loggers
            // ─────────────────────────────
            void AddLogger<T>(IServiceCollection svc) where T : class
                => svc.AddScoped(_ => _.GetRequiredService<ILoggerFactory>().CreateLogger<T>());

            // <conversacore-domain-topics>
            
            // Sample Topic (generated by template)
            AddLogger<SampleTopic>(services);
            services.AddScoped<ITopic>(sp => new SampleTopic(
                sp.GetRequiredService<TopicWorkflowContext>(),
                sp.GetRequiredService<ILogger<SampleTopic>>(),
                sp.GetRequiredService<IConversationContext>()
            ));
            
            // Custom Insurance Leads Agent Topics
            AddLogger<ConversationStartTopic>(services);
            services.AddScoped<ITopic>(sp => new ConversationStartTopic(
                sp.GetRequiredService<TopicWorkflowContext>(),
                sp.GetRequiredService<ILogger<ConversationStartTopic>>()
            ));
            
            AddLogger<LeadOrchestratorTopic>(services);
            services.AddScoped<ITopic>(sp => new LeadOrchestratorTopic(
                sp.GetRequiredService<TopicWorkflowContext>(),
                sp.GetRequiredService<ILogger<LeadOrchestratorTopic>>(),
                sp.GetRequiredService<ILoggerFactory>()
            ));
            
            AddLogger<EligibilityTopic>(services);
            services.AddScoped<ITopic>(sp => new EligibilityTopic(
                sp.GetRequiredService<TopicWorkflowContext>(),
                sp.GetRequiredService<ILogger<EligibilityTopic>>()
            ));
            
            AddLogger<IntakeTopic>(services);
            services.AddScoped<ITopic>(sp => new IntakeTopic(
                sp.GetRequiredService<TopicWorkflowContext>(),
                sp.GetRequiredService<ILogger<IntakeTopic>>(),
                sp.GetRequiredService<ILoggerFactory>()
            ));
            
            AddLogger<TransferTopic>(services);
            services.AddScoped<ITopic>(sp => new TransferTopic(
                sp.GetRequiredService<TopicWorkflowContext>(),
                sp.GetRequiredService<ILogger<TransferTopic>>()
            ));
            // </conversacore-domain-topics>
        }

        public static void AddConversaCoreDocumentIngestion(this IServiceCollection services)
        {
            // <conversacore-document-ingestion>
            // Document ingestion services and coordinator will be registered here
            // by the ConversaCore Topic Tool based on .conversacore.documents.json.
            // </conversacore-document-ingestion>
        }
    }
}
