using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Web;
using ConversaCore;
using ConversaCore.UI.Services;
using ConversaCore.Interfaces;
using ConversaCore.SystemTopics;
using ConversaCore.Topics;
using ConversaCore.Context;
using ConversaCore.TopicFlow;
using Microsoft.Extensions.Logging;
using ConversaCore.BlazorTemplateHost.Services;
using ConversaCore.BlazorTemplateHost.Configuration;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddRazorPages();
builder.Services.AddServerSideBlazor();

// Add ConversaCore (framework only, no domain UI yet)
var openAIApiKey = Environment.GetEnvironmentVariable("OPENAI_API_KEY") ?? "demo-key";
builder.Services.AddConversaCore(
    openAIApiKey: openAIApiKey,
    embeddingModel: "text-embedding-3-small"
);

// Add ConversaCore.UI services
builder.Services.AddScoped<IChatInteropService, ChatInteropService>();

// Register domain-specific agent
builder.Services.AddScoped<ConversaCore.Agentic.DomainAgentService, MyDomainAgentService>();
builder.Services.AddScoped<MyDomainAgentService>(sp =>
    (MyDomainAgentService)sp.GetRequiredService<ConversaCore.Agentic.DomainAgentService>()
);

// Register system topics
void AddLogger<T>(IServiceCollection svc) where T : class
    => svc.AddScoped(_ => _.GetRequiredService<ILoggerFactory>().CreateLogger<T>());

AddLogger<ConversationStartTopic>(builder.Services);
builder.Services.AddScoped<ITopic>(sp => new ConversationStartTopic(
    sp.GetRequiredService<TopicWorkflowContext>(),
    sp.GetRequiredService<ILogger<ConversationStartTopic>>(),
    sp.GetRequiredService<IConversationContext>()
));

AddLogger<FallbackTopic>(builder.Services);
builder.Services.AddScoped<ITopic>(sp => new FallbackTopic(
    sp.GetRequiredService<TopicWorkflowContext>(),
    sp.GetRequiredService<ILogger<FallbackTopic>>(),
    sp.GetRequiredService<Microsoft.SemanticKernel.Kernel>(),
    sp.GetService<IVectorDatabaseService>()
));

AddLogger<OnErrorTopic>(builder.Services);
builder.Services.AddScoped<ITopic>(sp => new OnErrorTopic(
    sp.GetRequiredService<TopicWorkflowContext>(),
    sp.GetRequiredService<ILogger<OnErrorTopic>>()
));

AddLogger<MultipleTopicsMatchedTopic>(builder.Services);
builder.Services.AddScoped<ITopic>(sp => new MultipleTopicsMatchedTopic(
    sp.GetRequiredService<TopicWorkflowContext>(),
    sp.GetRequiredService<ILogger<MultipleTopicsMatchedTopic>>()
));

AddLogger<SignInTopic>(builder.Services);
builder.Services.AddScoped<ITopic>(sp => new SignInTopic(
    sp.GetRequiredService<TopicWorkflowContext>(),
    sp.GetRequiredService<ILogger<SignInTopic>>()
));

AddLogger<ResetConversationTopic>(builder.Services);
builder.Services.AddScoped<ITopic>(sp => new ResetConversationTopic(
    sp.GetRequiredService<TopicWorkflowContext>(),
    sp.GetRequiredService<ILogger<ResetConversationTopic>>()
));

AddLogger<EscalateTopic>(builder.Services);
builder.Services.AddScoped<ITopic>(sp => new EscalateTopic(
    sp.GetRequiredService<TopicWorkflowContext>(),
    sp.GetRequiredService<ILogger<EscalateTopic>>()
));

AddLogger<EndOfConversationTopic>(builder.Services);
builder.Services.AddScoped<ITopic>(sp => new EndOfConversationTopic(
    sp.GetRequiredService<TopicWorkflowContext>(),
    sp.GetRequiredService<ILogger<EndOfConversationTopic>>()
));

// Register domain topics via central helper
builder.Services.AddConversaCoreDomainTopics();

// Register document ingestion services and coordinator (generated by the Topic Tool)
builder.Services.AddConversaCoreDocumentIngestion();

var app = builder.Build();

// Configure the topic registry with all DI-registered topics
try
{
    using var scope = app.Services.CreateScope();
    var topicRegistry = scope.ServiceProvider.GetRequiredService<TopicRegistry>();
    topicRegistry.ConfigureTopics(scope.ServiceProvider);
    Console.WriteLine("Topic configuration complete (ConversaCore.BlazorTemplateHost)");

    // Sample: run document ingestion at startup (design-time / ops only)
    // var coordinator = scope.ServiceProvider.GetService<YourApp.Services.DocumentIngestionCoordinator>();
    // if (coordinator != null)
    // {
    //     await coordinator.RunAllCollectionsAsync();
    // }
}
catch (Exception ex)
{
    Console.WriteLine($"Topic configuration ERROR: {ex}");
}

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseHttpsRedirection();

app.UseStaticFiles();

app.UseRouting();

app.MapBlazorHub();
app.MapFallbackToPage("/_Host");

app.Run();
