using System.Text.Json;
using System.Text.Json.Serialization;
using ConversaCore.Interfaces;

namespace InsuranceAgent.DomainTypes;

/// <summary>
/// Represents the structured eligibility output generated by the SemanticQueryActivity.
/// This model defines exactly what the AI should return after applying underwriting rules.
/// </summary>
public class QualifiedCarriers : IDomainOutput {
    /// <summary>
    /// List of evaluated carriers and their corresponding eligibility determinations.
    /// </summary>
    [JsonPropertyName("carriers")]
    public List<CarrierEligibility> Carriers { get; set; } = new();

    // ================================================================
    // IDomainOutput IMPLEMENTATION
    // ================================================================
    [JsonIgnore]
    public string OutputId => $"qualified-carriers-{Guid.NewGuid():N}";

    [JsonIgnore]
    public string OutputType => nameof(QualifiedCarriers);

    public string ToJson() => JsonSerializer.Serialize(this, new JsonSerializerOptions {
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
    });

    public Dictionary<string, object> GetMetadata() => new() {
        ["carrierCount"] = Carriers.Count,
        ["outputType"] = OutputType
    };

    public override string ToString() => $"QualifiedCarriers({Carriers.Count})";
}

/// <summary>
/// Represents a single carrier's underwriting decision.
/// </summary>
public class CarrierEligibility {
    // === Core fields ===
    [JsonPropertyName("carrierName")]
    public string CarrierName { get; set; } = string.Empty;

    [JsonPropertyName("eligibility")]
    public string Eligibility { get; set; } = "Uncertain";

    [JsonPropertyName("rationale")]
    public List<string> Rationale { get; set; } = new();

    [JsonPropertyName("uncertaintyReason")]
    public string? UncertaintyReason { get; set; }

    [JsonPropertyName("confidenceScore")]
    public double? ConfidenceScore { get; set; }

    [JsonPropertyName("matchedConditions")]
    public List<string>? MatchedConditions { get; set; }

    [JsonPropertyName("rejectedConditions")]
    public List<string>? RejectedConditions { get; set; }

    // === Optional UI metadata (for display / ranking) ===

    [JsonPropertyName("productName")]
    public string? ProductName { get; set; }

    [JsonPropertyName("coverageAmount")]
    public string? CoverageAmount { get; set; }

    [JsonPropertyName("estimatedMonthlyPremium")]
    public int? EstimatedMonthlyPremium { get; set; }

    [JsonPropertyName("matchScore")]
    public int? MatchScore { get; set; }
}
